### ISSUE TITLE
Cannot publish my demo

### ISSUE THREAD

**Issue by jfmonteil** [Pentaho-SE-EMEA-APAC/part#195]
Error Failed to swithc to change (develop branch)

[part.previous.log](https://gist.github.com/c8b6ffe3f9a97a004418493680a01461)

**Comment by jfmonteil** [comment]
```
C:\Users\jmonteil\.part\part.log
INFO : PART command: publish
Please enter your GitHub username: jfmonteil@gmail.com
Please enter your GitHub password:
Please enter your GitHub email: jfmonteil@gmail.com
TRACE: Main JAR path: /C:/Program Files/part/part.jar
INFO : Pushing asset files (to GitHub)
TRACE: Entered initialiseCaptureRepository for folder: C:\Program Files\part\demo-madrid-smart-city
TRACE: Repo short name: demo-madrid-smart-city
WARN : Asset folder already initialised for git: 'C:\Program Files\part\demo-madrid-smart-city\.git'
TRACE: Loading local git folder
TRACE: Got git folder reference
TRACE: Not on develop branch, on 'master', switching to develop branch called 'develop'
TRACE: Got stash name '77d6d21cae64f3d398442a6eeae25b0e2e1e7653'
FATAL: Failed to switch to change (develop) branch
org.eclipse.jgit.api.errors.RefNotFoundException: Ref develop cannot be resolved
        at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:254)
        at org.pentaho.part.versioning.GitManager.initialiseCaptureRepository(GitManager.java:172)
        at org.pentaho.part.commands.PublishCommand.execute(PublishCommand.java:219)
        at org.pentaho.part.Part.main(Part.java:196)
FATAL: Error initialising demo asset Git repository on Local machine
INFO : publish failed to completed successfully
INFO : publish completed in 65,082 seconds

```
Not sure what I should do here, I had the following when publishing the first time 

```
C:\Program Files\part\demo-madrid-smart-city>part publish -version 0.1
C:\Users\jmonteil\.part\part.log
INFO : PART command: publish
Please enter your GitHub username: jmonteil@gmail.com
Please enter your GitHub password:
Please enter your GitHub email: jfmonteil@gmail.com
INFO : Pushing asset files (to GitHub)
FATAL: Problem verifying user is a member of organisation 'Pentaho-SE-EMEA-APAC'
org.eclipse.egit.github.core.client.RequestException: Bad credentials (401)
        at org.eclipse.egit.github.core.client.GitHubClient.createException(GitHubClient.java:583)
        at org.eclipse.egit.github.core.client.GitHubClient.get(GitHubClient.java:776)
        at org.eclipse.egit.github.core.service.GitHubService.check(GitHubService.java:193)
        at org.eclipse.egit.github.core.service.OrganizationService.isMember(OrganizationService.java:258)
        at org.pentaho.part.versioning.GitManager.initialiseCaptureRepository(GitManager.java:209)
        at org.pentaho.part.commands.PublishCommand.execute(PublishCommand.java:219)
        at org.pentaho.part.Part.main(Part.java:196)
FATAL: Error initialising demo asset Git repository on Local machine
INFO : publish failed to completed successfully
INFO : publish completed in 27,602 seconds

```

**Comment by adamfowleruk** [comment]
Your GitHub username IS NOT your email. You sent me the username so I could add you to the group. This broke your first checkin and attempted creation of a repo.

Delete the .git folder in your demo folder, and try part publish again.

**Comment by jfmonteil** [comment]
cheers !
